apiVersion: v1
kind: Service
metadata:
  name: playground-svc
  labels:
    app: playground
spec:
  type: ClusterIP
  selector:
    app: playground
  ports:
    - name: http
      port: 8888
      targetPort: 8888
